name: Build PR
run-name: "PR Build: #${{ github.event.pull_request.number }} (${{ github.run_attempt }}.${{ github.run_number }}) - ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      build-type: "PR"

  # This job is here to have only one final step to add for "Status Checks"
  # in GitHub, instead of adding every leaf test from 'build-test-package'
  final-check:
    needs: ['build']
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    runs-on: ubuntu-latest
    steps:
      - run: exit 1