name: Create Release Build
run-name: "Release Build: ${{ inputs.new-tag }}"

on:
  workflow_dispatch:
    inputs:
      new-tag:
        description: "New release tag"
        required: true

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  verify-release-tag:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify release tag
        run: |
          echo "Release tag to verify: ${{ inputs.new-tag }}"

          # Check if tag already exists:
          if git rev-parse ${{ inputs.new-tag }} >/dev/null 2>&1; then
            echo "❌ - Release tag already exists: ${{ inputs.new-tag }}"
            exit 1
          fi
          echo "✔ - Release tag does not exist"

          # Check if tag correct format:
          regex='^([0-9]+\.){2}(\*|[0-9]+)(-.*)?$'
          if [[ ! ${{ inputs.new-tag }} =~ $regex ]]; then
            echo "❌ - Release tag is not a valid semver: ${{ inputs.new-tag }}"
            exit 1
          fi
          echo "✔ - Release tag is a valid semver"

  release:
    needs: ['verify-release-tag']
    uses: "./.github/workflows/release.yml"
    secrets: inherit
    with:
      version: ${{ inputs.new-tag }}
