name: Reusable WF - Release

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  build-test-package:
    uses: "./.github/workflows/build-test-package.yml"
    secrets: inherit

  create-release:
    needs: ['build-test-package']
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.build-test-package.outputs.package-version }}
        commit: ${{ github.sha }}
        name: "Amalgam VSCode Plugin ${{ needs.build-test-package.outputs.package-version }}"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        makeLatest: legacy
        artifacts: "./amalgam-lang-*.vsix/amalgam-lang-*.vsix"